services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to access Docker
    networks:
      - jenkins-network  # Define the network

networks:
  jenkins-network:  # Define the network here
    driver: bridge

volumes:
  jenkins_home:
